version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn pydock.wsgi:application --bind 0.0.0.0:8888
    ports:
      - 8888:8888
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports: 
      - 5432:5432
    env_file:
      - ./.env.db

volumes:
  postgres_data:
