version: "3.7"

services:
  app:
    user: vscode
    image: krosf/dev-containers:python3.8-slim
    volumes:
      - ..:/home/vscode/workspace:cached
    command: sleep infinity
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: LocalPassword
